sudo: required
services:
   - docker
before_install:
   - docker build -t prasad/react-test -f ./client/Dockerfile.dev
script:
   - docker run prasad/react-test npm test -- --coverage
after_success:
   - docker build -t prasad/multi-client ./client
   - docker build -t prasad/multi-client ./nginx
   - docker build -t prasad/multi-client ./server
   - docker build -t prasad/multi-client ./worker
   
   echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   
   - docker push prasad/multi-client 
   - docker push prasad/multi-nginx
   - docker push prasad/multi-server
   - docker push prasad/multi-worker
