sudo: required
services:
   - docker
before_install:
   - docker build -t durga/react-test -f ./client/Dockerfile.dev
script:
   - docker run durga/react-test npm test -- --coverage
after_success:
   - docker build -t durga/multi-client ./client
   - docker build -t durga/multi-nginx ./nginx
   - docker build -t durga/multi-server ./server
   - docker build -t durga/multi-worker ./worker
   
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   
   - docker push durga/multi-client 
   - docker push durga/multi-nginx
   - docker push durga/multi-server
   - docker push durga/multi-worker
